### ISSUE TITLE
Sequencer event types MIDI2 vs MIDI1

### ISSUE THREAD

**Issue by symdeb** [tiwai/alsa-lib#6]
The SEQUENCER SND_SEQ_EVENT_UMP event for MIDI2  has same value (5) as SND_SEQ_EVENT_STOP  for MIDI1. There seems to be sufficient unused event types left. Curious to know why this was done so.
in a receive callback it is then not possible to know what type it is, a classic STOP or an UMP event.

**Comment by tiwai** [comment]
SND_SEQ_EVENT_UMP is no type but a bit flag set in ev->flags instead.
Check snd_seq_is_ump() macro.

**Comment by symdeb** [comment]
Thanks, how to check in a (sequencer) receive callback the event is a UMP event ?

**Comment by tiwai** [comment]
snd_seq_ev_is_ump().
